# old text + new text -> generate edit summary

_target_: src.openai.prompting.formatters.SimpleFormatter

# format definition of prompt
global_format: "{instruction}\n\n{demonstration}\n\n{query}\ncomment:"
query_format: "\"The input is:\ntext removed:\n{text1}\ntext added:\n{text2}\""
demonstration_format: "\"text removed:\n{text1}\ntext added:\n{text2}\ncomment:{target}\""
instruction: "You are presented with the edit of a Wikipedia article in a form of text that was removed and added. Give a brief summary of the edit in a form of a comment no longer than 15 words."
