data_dir: null
cache_dir: ${data_dir}/.cache # The default is ~/.cache/huggingface/datasets

debug: False
debug_k: 12

seed: ${seed}

_target_: src.datamodules.EditSummaryDataMudule # the datamodule class
batch_size: ??? # batch_size needs to be specified
num_workers: ??? # num_workers needs to be specified
use_prefix: true

# either dataset_target_ or dataset_parameters.*.dataset._target_ must be overloaded
dataset_target_: src.datamodules.EditSummaryDataset # the pytorch dataset class

filter_on_num_tokens: true
max_num_tokens_input: 512 
max_num_tokens_target: 512

dataset_parameters:
  test:
    dataset:
      _target_: ${datamodule.dataset_target_}
      seed: ${datamodule.seed}
      debug: ${datamodule.debug}
      debug_k: ${datamodule.debug_k}
      max_num_tokens_input: ${datamodule.max_num_tokens_input}
      max_num_tokens_target: ${datamodule.max_num_tokens_target}
      load_dataset_params:
        split: "test"
        data_dir: ${datamodule.data_dir}
        filter_on_num_tokens: ${datamodule.filter_on_num_tokens}
        use_prefix: ${datamodule.use_prefix}

    dataloader:
      batch_size: ${datamodule.batch_size}
      num_workers: ${datamodule.num_workers}
  train:
    dataset:
      _target_: ${datamodule.dataset_target_}
      seed: ${datamodule.seed}
      debug: ${datamodule.debug}
      debug_k: ${datamodule.debug_k}
      max_num_tokens_input: ${datamodule.max_num_tokens_input}
      max_num_tokens_target: ${datamodule.max_num_tokens_target}
      load_dataset_params:
        split: "train"
        data_dir: ${datamodule.data_dir}
        filter_on_num_tokens: ${datamodule.filter_on_num_tokens}
        use_prefix: ${datamodule.use_prefix}

    dataloader:
      batch_size: ${datamodule.batch_size}
      num_workers: ${datamodule.num_workers}
  val:
    dataset:
      _target_: ${datamodule.dataset_target_}
      seed: ${datamodule.seed}
      debug: ${datamodule.debug}
      debug_k: ${datamodule.debug_k}
      max_num_tokens_input: ${datamodule.max_num_tokens_input}
      max_num_tokens_target: ${datamodule.max_num_tokens_target}
      load_dataset_params:
        split: "val"
        data_dir: ${datamodule.data_dir}
        filter_on_num_tokens: ${datamodule.filter_on_num_tokens}
        use_prefix: ${datamodule.use_prefix}

    dataloader:
      batch_size: ${datamodule.batch_size}
      num_workers: ${datamodule.num_workers}